apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - deploy/kubernetes.yaml
configMapGenerator:
  - name: lina-quiz-site
    files:
      - web/index.html
      - web/style.css
      - web/quiz.js
      - web/app.js
      - questions.json
  - name: lina-quiz-nginx
    files:
      - default.conf=deploy/nginx.conf
